### ISSUE TITLE
Snowflake setup appears to be broken (copy from slack)

### ISSUE THREAD

**Issue by rsyi** [dataframehq/whale#130]
See #troubleshooting in slack.
Reposting the trace here:

```
Running ETL job manually.
2021-01-08 10:21:16,284:INFO:whale:ETL process started.
Traceback (most recent call last):
 File "/home/ec2-user/.whale/bin/../libexec/build_script.py", line 23, in <module>
  pull()
 File "/home/ec2-user/.whale/libexec/env/lib/python3.8/site-packages/whale/utils/task_wrappers.py", line 79, in pull
  connection = ConnectionConfigSchema(**raw_connection_dict)
TypeError: __init__() missing 1 required positional argument: 'metadata_source'
thread 'main' panicked at 'Can't read file `/home/ec2-user/.whale/manifests/manifest.txt`', src/filesystem.rs:30:29
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

**Comment by rsyi** [comment]
Cannot reproduce error, will debug in #troubleshooting (slack).
