### ISSUE TITLE
Crash after installation on wh pull

### ISSUE THREAD

**Issue by winzee** [dataframehq/whale#139]
Right after a `brew install dataframehq/tap/whale`. When I run `wh pull` I get:

```
Running ETL job manually.
Traceback (most recent call last):
  File "/usr/local/Cellar/whale/v1.5.1/bin/../libexec/build_script.py", line 5, in <module>
    from whale import pull
  File "/usr/local/Cellar/whale/v1.5.1/libexec/env/lib/python3.8/site-packages/whale/_init_.py", line 22, in <module>
    from whale.utils.extractor_wrappers import (
  File "/usr/local/Cellar/whale/v1.5.1/libexec/env/lib/python3.8/site-packages/whale/utils/extractor_wrappers.py", line 15, in <module>
    from whale.extractor.splice_machine_metadata_extractor import (
  File "/usr/local/Cellar/whale/v1.5.1/libexec/env/lib/python3.8/site-packages/whale/extractor/splice_machine_metadata_extractor.py", line 12, in <module>
    from splicemachinesa.pyodbc import splice_connect
  File "/usr/local/Cellar/whale/v1.5.1/libexec/env/lib/python3.8/site-packages/splicemachinesa/_init_.py", line 1, in <module>
    from . import splice_machine, pyodbc, base
  File "/usr/local/Cellar/whale/v1.5.1/libexec/env/lib/python3.8/site-packages/splicemachinesa/pyodbc.py", line 2, in <module>
    from pyodbc import connect as odbc_connect
ImportError: dlopen(/usr/local/Cellar/whale/v1.5.1/libexec/env/lib/python3.8/site-packages/pyodbc.cpython-38-darwin.so, 2): Library not loaded: /usr/local/opt/unixodbc/lib/libodbc.2.dylib
  Referenced from: /usr/local/Cellar/whale/v1.5.1/libexec/env/lib/python3.8/site-packages/pyodbc.cpython-38-darwin.so
  Reason: image not found
thread 'main' panicked at 'Can't read file /Users/lmg/.whale/manifests/manifest.txt', src/filesystem.rs:29:29
note: run with RUST_BACKTRACE=1 environment variable to display a backtrace
```

The connections.yaml file is like follow:

```
---
name: bq-1
metadata_source: Bigquery
key_path: ~/.whale/quite_a_long_filename1.json
project_credentials: ~
project_id: l*-*****-***7
---
name: bq-1
metadata_source: Bigquery
key_path: ~/.whale/quite_a_long_filename2.json
project_credentials: ~
project_id: a***-*****-****7
```

OSX 10.15.7

**Comment by rsyi** [comment]
Hey @winzee! It looks like in other instances this problem is a result of not having unixodbc installed. Could you try running the following, then try `wh pull` again?

```
brew install unixodbc
```

If this works, feel free to update the docs! Should be an easy PR if you feel like contributing 😉  (Also happy to do it myself, but trying to be less dictatorial with fixes 🙂)

On a side note, we are also starting to get a bit heavy with the dependencies... I'll have to think about how to get around this...
