### ISSUE TITLE
Error when running wh pull

### ISSUE THREAD

**Issue by timrcase** [dataframehq/whale#152]
I"m getting the error below when trying to run `wh pull` after completing a `wh init` to create a connection against our Snowflake warehouse.

```
❯ wh pull
Running ETL job manually.
Traceback (most recent call last):
  File "/usr/local/Cellar/whale/v1.5.1/bin/../libexec/build_script.py", line 5, in <module>
    from whale import pull
  File "/usr/local/Cellar/whale/v1.5.1/libexec/env/lib/python3.8/site-packages/whale/__init__.py", line 22, in <module>
    from whale.utils.extractor_wrappers import (
  File "/usr/local/Cellar/whale/v1.5.1/libexec/env/lib/python3.8/site-packages/whale/utils/extractor_wrappers.py", line 15, in <module>
    from whale.extractor.splice_machine_metadata_extractor import (
  File "/usr/local/Cellar/whale/v1.5.1/libexec/env/lib/python3.8/site-packages/whale/extractor/splice_machine_metadata_extractor.py", line 12, in <module>
    from splicemachinesa.pyodbc import splice_connect
  File "/usr/local/Cellar/whale/v1.5.1/libexec/env/lib/python3.8/site-packages/splicemachinesa/__init__.py", line 1, in <module>
    from . import splice_machine, pyodbc, base
  File "/usr/local/Cellar/whale/v1.5.1/libexec/env/lib/python3.8/site-packages/splicemachinesa/pyodbc.py", line 2, in <module>
    from pyodbc import connect as odbc_connect
ImportError: dlopen(/usr/local/Cellar/whale/v1.5.1/libexec/env/lib/python3.8/site-packages/pyodbc.cpython-38-darwin.so, 2): Library not loaded: /usr/local/opt/unixodbc/lib/libodbc.2.dylib
  Referenced from: /usr/local/Cellar/whale/v1.5.1/libexec/env/lib/python3.8/site-packages/pyodbc.cpython-38-darwin.so
  Reason: image not found
thread 'main' panicked at 'Can't read file `/Users/P2137616/.whale/manifests/manifest.txt`', src/filesystem.rs:29:29
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

**Comment by rsyi** [comment]
Ah thanks for highlighting this, @timrcase. I suspect it's an odbc dependency issue (sounds similar to https://github.com/dataframehq/whale/issues/139.)

Could you share a little bit more about your setup? Are you on OSX? Linux?

If you're on OSX, you could run:
```
brew install unixodbc
```

And that should solve this. I'll throw up a ticket to update the docs accordingly. In the future, we should definitely get around this, though, by having explicit install flags -- pyodbc doesn't need to be a dependency if you're using Snowflake. I'll think through the optimal pattern a bit more...

**Comment by timrcase** [comment]
Installing `unixodbc` resolved the issue. I appreciate the quick response.

**Comment by timrcase** [comment]
@rsyi I just opened a [PR](https://github.com/dataframehq/homebrew-tap/pull/27) to add `unixodbc` as a dependency in the homebrew formulae to help prevent this issue for now.

**Comment by rsyi** [comment]
Thanks, @timrcase ! Great idea :) Merged!
