### ISSUE TITLE
Error when try get data from Glue Catalog

### ISSUE THREAD

**Issue by rubenssoto** [dataframehq/whale#54]
Hello,

I'm trying to get metadata from glue catalog and I got this error:

Traceback (most recent call last):
  File "/usr/local/Cellar/whale/v1.1.0/bin/../libexec/build_script.py", line 20, in <module>
    pull()
  File "/usr/local/Cellar/whale/v1.1.0/libexec/env/lib/python3.8/site-packages/whale/utils/task_wrappers.py", line 107, in pull
    task.run()
  File "/usr/local/Cellar/whale/v1.1.0/libexec/env/lib/python3.8/site-packages/whale/task/__init__.py", line 26, in run
    record = self.transformer.transform(record)
  File "/usr/local/Cellar/whale/v1.1.0/libexec/env/lib/python3.8/site-packages/whale/transformer/markdown_transformer.py", line 118, in transform
    return formatter(record)
  File "/usr/local/Cellar/whale/v1.1.0/libexec/env/lib/python3.8/site-packages/whale/transformer/markdown_transformer.py", line 29, in format_table_metadata
    description = record.description + "\n"
TypeError: unsupported operand type(s) for +: 'DescriptionMetadata' and 'str'
thread 'main' panicked at 'Can't read file.: Os { code: 2, kind: NotFound, message: "No such file or directory" }', src/filesystem.rs:27:50
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

Thank you

**Comment by rsyi** [comment]
Ah okay. It looks like this just happens when you have descriptions within Glue. This is what happens when I only test against a dummy instance without any data. :)

Fixing now, and will cut a new release in the next hour.

**Comment by wandersoncferreira** [comment]
Hello @rsyi thanks for the package. I got the same error when running the `pull` command towards a Redshift.

```
Running ETL job manually.
2020-10-23 14:40:29,183:INFO:whale:ETL process started.
2020-10-23 14:40:29,185:INFO:databuilder.extractor.base_postgres_metadata_extractor:SQL for postgres metadata: 
        SELECT
            *
        FROM (
            SELECT
              CURRENT_DATABASE() as cluster,
              c.table_schema as schema,
              c.table_name as name,
              pgtd.description as description,
              c.column_name as col_name,
              c.data_type as col_type,
              pgcd.description as col_description,
              ordinal_position as col_sort_order
            FROM INFORMATION_SCHEMA.COLUMNS c
            INNER JOIN
              pg_catalog.pg_statio_all_tables as st on c.table_schema=st.schemaname and c.table_name=st.relname
            LEFT JOIN
              pg_catalog.pg_description pgcd on pgcd.objoid=st.relid and pgcd.objsubid=c.ordinal_position
            LEFT JOIN
              pg_catalog.pg_description pgtd on pgtd.objoid=st.relid and pgtd.objsubid=0

            UNION

            SELECT
              CURRENT_DATABASE() as cluster,
              view_schema as schema,
              view_name as name,
              NULL as description,
              column_name as col_name,
              data_type as col_type,
              NULL as col_description,
              ordinal_position as col_sort_order
            FROM
                PG_GET_LATE_BINDING_VIEW_COLS()
                    COLS(view_schema NAME, view_name NAME, column_name NAME, data_type VARCHAR, ordinal_position INT)
        )

        
        ORDER by cluster, schema, name, col_sort_order ;
        
Traceback (most recent call last):
  File "/home/wand/.whale/bin/../libexec/build_script.py", line 20, in <module>
    pull()
  File "/home/wand/.whale/libexec/env/lib/python3.8/site-packages/whale/utils/task_wrappers.py", line 107, in pull
    task.run()
  File "/home/wand/.whale/libexec/env/lib/python3.8/site-packages/whale/task/__init__.py", line 26, in run
    record = self.transformer.transform(record)
  File "/home/wand/.whale/libexec/env/lib/python3.8/site-packages/whale/transformer/markdown_transformer.py", line 118, in transform
    return formatter(record)
  File "/home/wand/.whale/libexec/env/lib/python3.8/site-packages/whale/transformer/markdown_transformer.py", line 29, in format_table_metadata
    description = record.description + "\n"
TypeError: unsupported operand type(s) for +: 'DescriptionMetadata' and 'str'
thread 'main' panicked at 'Can't read file.: Os { code: 2, kind: NotFound, message: "No such file or directory" }', src/filesystem.rs:27:50
stack backtrace:
   0: rust_begin_unwind
             at /build/rust/src/rustc-1.47.0-src/library/std/src/panicking.rs:475
   1: core::panicking::panic_fmt
             at /build/rust/src/rustc-1.47.0-src/library/core/src/panicking.rs:85
   2: core::option::expect_none_failed
             at /build/rust/src/rustc-1.47.0-src/library/core/src/option.rs:1221
   3: whale::filesystem::deduplicate_file
   4: whale::Whale::etl
   5: whale::main
```

**Comment by rsyi** [comment]
Yes! @wandersoncferreira, this should be fixed now - thanks for the callout. Try a reinstall of the latest version and it should work.

**Comment by wandersoncferreira** [comment]
I had just cloned. Missed the fix because of some minutes, lol. All working great! thanks

**Comment by rsyi** [comment]
lol what good/bad timing. Either way, really appreciate you and @rubenssoto surfacing the issue. :)

Let me know if I can be of any help (and if want to have a more involved discussion, check out our slack channel!).
